workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60
    environment:
      sdk: 30
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
